### ISSUE TITLE
Morning session: peer-to-peer code reviews

### ISSUE THREAD

**Issue by jaflih** [clintonjosephs/to-do-list#12]
Hello @clintonjosephs, You have made a great job till 💯 now however I would like to mention some points to change:

- the drag and drop works but we don't want to swap 2 tasks, we want to move only one task and so update the index of all tasks.

**Comment by clintonjosephs** [comment]
Thank you so much for pointing this out @jihaneH, I have refactored the drag-drop class accordingly. ☺️
